### ISSUE TITLE
CSV text is truncated, can full_text be included?

### ISSUE THREAD

**Issue by dreboy493** [DocNow/hydrator#60] opened 2020-09-16 10:42 UTC

**Comment by opendatasurgeon** [comment] 2020-10-05 19:52
You should double check the spellings before you post something and please provide little more information. Anyways, yes the default .csv from Hydrator will have the text column truncated (only for the tweets that are RT I believe, some one double check me), but you can read this jsonl file in an R or python environment, and get the `full_text` column, which contain full texts for the tweets. Good luck, Cheers.

**Comment by edsu** [comment] 2020-10-05 20:18
This is a duplicate of #26 -- it needs to be done though!

**Closed by edsu** 2020-10-05 20:18 UTC
