### ISSUE TITLE
Cannot link to twitter account in 3.0 version.

### ISSUE THREAD

**Issue by Jasaxion** [DocNow/hydrator#116] opened 2021-12-30 10:25 UTC
Click the "Link To Twitter account" is invalid.

version: Hydrator-Setup-0.3.0.exe  // Windows 10

**Comment by edsu** [comment] 2021-12-30 19:04
I just tried it on OS X and it worked fine. I don't have a Windows machine to test with unfortunately. Can you take some screenshots to describe what the problem is you are seeing? Also if you are in China then #114 might be the problem.

**Comment by Jasaxion** [comment] 2022-01-01 13:10
![image](https://user-images.githubusercontent.com/32972730/147851019-4ce8a3e8-20c5-4bcc-8b88-ac9f7666e84b.png)
I also try to use Ubuntu to test, but the problem still.
I am in China now, maybe it is the problem of proxy. (because I have to use the VPN to connect to twitter)
I am a student in China, sorry for my english if my expression is inappropriate and thanks a lot to help me😁.

**Comment by edsu** [comment] 2022-04-22 15:11
Sorry, it is a proxy problem. Duplicate of #114

**Closed by edsu** 2022-04-22 15:11 UTC
