### ISSUE TITLE
Overflow of tweet id, Hydrator keeps extracting the tweets

### ISSUE THREAD

**Issue by Gautamshahi** [DocNow/hydrator#66] opened 2020-10-26 20:45 UTC
Hi,

Hydrator keeps extracting the tweets, is there any solution to deal with it?

![image](https://user-images.githubusercontent.com/3966230/97226567-734f1400-17d4-11eb-86b4-95db8b39d1ed.png)

**Comment by edsu** [comment] 2020-10-26 21:35
Duplicate of #61

**Closed by edsu** 2020-10-26 21:35 UTC
