### ISSUE TITLE
Fewer Tweets in CSV than hydrated

### ISSUE THREAD

**Issue by Tom1316** [DocNow/hydrator#88] opened 2021-04-29 20:16 UTC
After hydration, I end up with Tweet Ids Read: 8,145,625/Tweets Hydrated: 7,583,036 which is to be expected. However, when I opened the CSV in R, I only had 2,586,793 observations. Why is there such a large discrepancy?  Does this mean over half the Tweets are not being converted?

**Comment by edsu** [comment] 2021-04-29 22:16
Hmm, that's not good. Are you able to share the CSV privately with me at ehs@pobox.com for me to take a look? Also can you point me at the tweet ids?

**Comment by Tom1316** [comment] 2021-04-29 22:35
Sure thing, however the CSV files i 1.5-ish GB, so I'll have to upload it to Google Drive first. Once this is done (in about an hour) I'll send you a link. The Tweet IDs were taken from the following [database](url):https://zenodo.org/record/4726282. I collected every Tweet ID between 7-14 April as .txt files. I then concatenated the individual textfiles into one text file, and ran it through the hydrator.  The JSONL is about 35GB, which is large compared to the CSV. I'm trying to look at ways to load the JSONL into R, but I'm very new to computational work and am struggling to figure out what to do.  - Thank you for your help

**Comment by edsu** [comment] 2021-04-29 23:32
I can confirm that there are 2,586,794 rows in he CSV you shared. Could you share the tweet id file and I will try with the Hydrator too. If you like I can also try hydrating with twarc which can be a bit more reliable for large datasets.

**Comment by Tom1316** [comment] 2021-04-30 06:45
OK, Ed, I'll email the file to you shortly. Does this mean the JSON produced by Hydrator is also corrupt or only the CSV? I'm hoping to use this dataset for my dissertaion, so would appreciate it if you could run it in twarc and send me the CSV.

**Comment by edsu** [comment] 2021-04-30 11:46
Ok, let me know when you send the tweet ids.

I'm not sure if the JSON is corrupt, but it's possible. One way to check would be to run a little program over it and count the lines that have a valid JSON object on them. If you have Python installed and your JSON file is called for example `tweets.jsonl` you could run a program like this.

```python

import json

count = 0
for line in open('tweets.jsonl'):
    tweet = json.loads(line)
    count += 1

print(count)
```

**Comment by Tom1316** [comment] 2021-04-30 12:59
Hi Ed,

The tweet ids should be in the link sent in my previous email. If it didn't
sen or open, I'll compress it and attach via email. Thank you for the
python script, I'll give it a try. I'm trying to run oen the json in R but
im getting memory errors.

Best Tom

**Comment by Tom1316** [comment] 2021-04-30 16:52
Hi Ed,

Thank you so much for this. Surprisingly, the CSV conversion was pretty
rapid; maybe that was the issue? If there's a way to send you an error log
I'd be to support however I could. It's encouraging that the number of JSON
objects matches the hydrated Tweets.

I would be most grateful if you'd be able to run it and send the CSV.
Afterwards I can try and open in it R and manipulate it from there. When
I'm not against a deadline, I'll try the py utility as I need to keep
developing my skills. I've passed it onto my classmates as I know a couple
of them want to deal with JSON objects.

Once again I can't thank you enough for your support, it really means a lot!

Best, Tom

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by edsu** [comment] 2021-04-30 17:37
Ok, I will respond with a private email with the link to the CSV. Let me know if you are able to read this with R. It will be a large DataFrame, so depending on your setup/resources it might make sense to subset just the data you need before loading it. The csvcut utility from [csvkit](https://csvkit.readthedocs.io/en/latest/) might provide a nice way to do that.

**Comment by Tom1316** [comment] 2021-04-30 19:32
It worked perfectly and the dataframe has fully loaded. Thanks for the assist. I'll take your advice and probably look to split the dataframe into quarters, process it and re-combine it.

**Comment by edsu** [comment] 2021-04-30 20:38
Since we have #56 and #51 for problems knowing how long CSV generation is taking can we close this ticket?

**Comment by Tom1316** [comment] 2021-05-01 09:08
Yes, thank you for your help.

**Closed** 2021-09-20 14:40 UTC
